### ISSUE TITLE
Get ten more cards then the set contains

### ISSUE THREAD

**Issue by davidsoderberg** [Harubex/scryfall#1]
Hi, when I use your package I get 10 more cards then the sets contains.
Kaladesh contains 264 but with your package I get 274, why?

**Comment by crookedneighbor** [comment]
According to scryfall it's 274: https://scryfall.com/sets/kld?as=grid&order=name

This is because the set includes cards that aren't opened in boosters, like [Chandar, Pyrogenius](https://scryfall.com/card/kld/265) which came in the planeswalker decks. You can see the 10 extra cards at the top of this list: https://scryfall.com/sets/kld?order=set&dir=asc&as=grid
